# Generated by Django 3.2.9 on 2021-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('bill', models.FileField(upload_to='bills/%Y/%m/%d/')),
            ],
        ),
    ]
