# Generated by Django 3.2.9 on 2021-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybills',
            name='bill',
            field=models.TextField(default=''),
        ),
    ]
