# Generated by Django 3.2.9 on 2021-12-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
