# Generated by Django 3.2.9 on 2021-12-21 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0002_students_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
