# Generated by Django 3.2.9 on 2021-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_ticket_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='latest_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='latest_bill',
            field=models.CharField(default='', max_length=20),
        ),
    ]
