# Generated by Django 3.2.9 on 2021-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20211223_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acceptance_date',
            field=models.DateTimeField(null=True),
        ),
    ]
